name: flutter_app_template
description: "Template for flutter app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  http: ^1.2.2
  http_interceptor: ^2.0.0
  riverpod_annotation: ^2.6.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true